export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const CONFIRM_ROUTE = '/confirm'
export const POSTS_ROUTE = '/'
export const POST_ROUTE = '/post'
export const SELFEDIT_ROUTE = '/selfedit'
export const USER_ROUTE = '/user'
